FROM public.ecr.aws/docker/library/node:14-alpine3.13

WORKDIR /app

COPY ./package.json .

COPY ./package-lock.json .

RUN npm install

COPY . .

RUN cp src/publications/ee/robots.txt src/

RUN cp src/publications/ee/index.html src/

RUN cp src/publications/ee/variables.scss src/assets/scss/

RUN cp src/publications/ee/publication.scss src/assets/scss/

RUN cp src/publications/ee/manifest.webmanifest src/

RUN cp -r src/publications/ee/icons src/assets

RUN npm run build:ee:prod

VOLUME /app/dist/1851/browser

RUN chown node:node -R /app/dist

EXPOSE 4000

USER node

CMD npm run serve:ssr