export const environment = {
  production: true,
  apiUrl: 'https://api.stachecow.nlasandbox2.info/v1',
  api2Url: 'https://api2.stachecow.nlasandbox2.info/v1',
  s3Url: 'https://dmprqkmvewks9.cloudfront.net/',
  apiGatewayUrl:'https://api.stachecow.nlasandbox2.info/v1',
  imageResizeUrl: 'https://d2x2scmkn9im41.cloudfront.net',
  reCaptchaKey: '6LfMfnkeAAAAADzHNgZIgnJvPHa-UIDpHMHCXkcN',
  rollbarKey: '3cc33cf350c9499681a19d63d6923644',
  appUrl: 'https://stachecow.nlasandbox2.info',
  fbUrl: 'https://www.facebook.com/stachecow/',
  port: 4700,
  enableSW: false,
  env: 'development',
};