FROM public.ecr.aws/docker/library/node:14-alpine3.13

WORKDIR /app

COPY ./package.json .

COPY ./package-lock.json .

RUN npm install

COPY . .

RUN cp src/publications/stachecow/index.html src/

RUN cp src/publications/stachecow/variables.scss src/assets/scss/

RUN cp src/publications/stachecow/publication.scss src/assets/scss/

RUN cp src/publications/stachecow/manifest.webmanifest src/

RUN cp -r src/publications/stachecow/icons src/assets

RUN npm run build:sc:qa

VOLUME /app/dist/1851/browser

RUN chown node:node -R /app/dist

EXPOSE 4700

USER node

CMD npm run serve:ssr