FROM public.ecr.aws/docker/library/node:14-alpine3.13

WORKDIR /app

COPY ./package.json .

COPY ./package-lock.json .

RUN npm install

COPY . .

RUN cp src/publications/1851/index.html src/

RUN cp src/publications/1851/variables.scss src/assets/scss/

RUN cp src/publications/1851/publication.scss src/assets/scss/

RUN cp src/publications/1851/manifest.webmanifest src/

RUN cp -r src/publications/1851/icons src/assets

RUN npm run build:1851:qa

VOLUME /app/dist/1851/browser

RUN chown node:node -R /app/dist

EXPOSE 4000

USER node

CMD npm run serve:ssr